In [14]:
import numpy as np
import numpy.linalg as lin
import time
A=np.loadtxt("in.txt",delimiter=" ")
n=A.shape[1]
M=np.loadtxt("in.txt",delimiter=" ")
y_0=np.random.rand(3)# первое приближение(случайный вектор)
y_0=y_0/lin.norm(y_0)
eps=1e-9
k=0

### Исходная матрица

In [15]:
M

array([[-0.820053, -0.135416,  0.269479],
       [-0.135416,  0.514864,  0.027061],
       [ 0.269479,  0.027061, -0.833651]])

In [16]:
np.triu(abs(M),k=1)

array([[0.      , 0.135416, 0.269479],
       [0.      , 0.      , 0.027061],
       [0.      , 0.      , 0.      ]])

### Поиск макс. эл.

In [17]:
def maxind(A):
    Diag=np.triu(abs(A),k=1)# обнуление нижних компонент
    ind = np.unravel_index(np.argmax(Diag, axis=None), Diag.shape)# индекс максмимального элемента
    return ind

In [19]:
X=np.identity(n)# единичная матрица

## Метод Якоби

In [20]:
start=time.time()
while abs(A[maxind(A)])>eps:
    V=np.identity(n)# будущая матрица поворта
    i=maxind(A)[0]# строка где находится макимальный элемент
    j=maxind(A)[1]# столбец где находится макс элемент
    d=np.sqrt((A[i,i]-A[j,j])**2+4*A[i,j]**2)# формлы для матрицы V()
    c=np.sqrt((1+abs(A[i,i]-A[j,j])/d)/2)
    s=np.sign(A[i,j]*(A[i,i]-A[j,j]))*np.sqrt((1-abs(A[i,i]-A[j,j])/d)/2)
    k+=1
    lamd=A[i,i]
    V[i,i]=c
    V[j,j]=c
    V[i,j]=-s
    V[j,i]=s
    X=X@V# для нахождения собственных векторов
    A=np.transpose(V)@A@V
end=time.time()
end-start    
    

0.0012128353118896484

In [21]:
lamds=[A[i,i] for i in range(3)]
S_Vect=[X[:,i] for i in range(3)]
Norm_Vect_nev=[np.max(M@S_Vect[i]-lamds[i]*S_Vect[i]) for i in range(3)]

Количество итераций

In [22]:
k

6

### С.ч.

In [23]:
lamds

[-0.5628168212209222, 0.5284622834463897, -1.1044854622254674]

### С.в.

In [24]:
S_Vect

[array([0.70356816, 0.07065113, 0.70710697]),
 array([-9.99160346e-02,  9.94995872e-01,  2.27752758e-07]),
 array([-0.7035685 , -0.07065148,  0.70710659])]

### Невязка

In [25]:
Norm_Vect_nev

[6.676874608757544e-10, -2.3714363805993344e-13, -6.684143516455521e-11]